FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY ["Lumina.Api.csproj", "./"]
RUN dotnet restore "Lumina.Api.csproj"

COPY . .
RUN dotnet publish "Lumina.Api.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS final
WORKDIR /app
EXPOSE 5006

COPY --from=build /app/publish .

ENTRYPOINT ["dotnet", "Lumina.Api.dll"]